settings:
  name: gosst
  repos:
    - https://github.com/sigstore/cosign
    - https://github.com/sigstore/rekor
    - https://github.com/sigstore/fulcio
    - https://github.com/google/oss-fuzz

collections:
  - id: Pull Requests
    name: Sigstore PRs
    description: >
     Pull requests in need of attention
    rules:
      - prs-cosign
      - prs-fulcio
      - prs-rekor
      - pr-approved-stale
      - pr-unapproved-stale
  - id: PRs - fuzzing
    name: OSS Fuzz PRs
    description: >
      Status of PRs in OSS-Fuzz
    rules:
      - prs-fuzz
      - fuzz-pr-approved-stale
      - fuzz-pr-unapproved-stale
  - id: Issues
    name: Issues
    dedup: true
    description: >
      Status of issues across repos
    rules:
      # Bugs
      - bugs
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      - issue-zombies
      # Issues needing closure
      - issue-stale-needs-info
      - issue-stale-support
      - lifecycle-rotten
      # People with questions
      - issue-has-question
      - issue-updated-support


rules:
  ### Pull requests
  prs-cosign:
    name: "Cosign PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/cosign

  prs-fulcio:
    name: "Fulcio PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/fulcio

  prs-rekor:
    name: "Rekor PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/rekor

  prs-fuzz:
    name: "OSS Fuzz PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!(changes-requested|draft|approved)"
    repos:
      - https://github.com/google/oss-fuzz

  # PR's needing closure
  fuzz-pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    resolution: "Merge PR"
    type: pull_request
    filters:
      - label: "approved"
      - updated: +2d
      - responded: +1d
    repos:
      - https://github.com/google/oss-fuzz

  fuzz-pr-unapproved-stale:
    name: "Pull Requests: Stale"
    resolution: "Add comment and/or close PR"
    type: pull_request
    filters:
      - created: +3d
      - updated: +2d
      - responded: +1d
      - tag: "!draft"
    repos:
      - https://github.com/google/oss-fuzz

  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    resolution: "Merge PR"
    type: pull_request
    filters:
      - label: "approved"
      - updated: +5d
      - responded: +2d

  pr-unapproved-stale:
    name: "Pull Requests: Stale"
    type: pull_request
    resolution: "Add comment and/or close PR"
    filters:
      - created: +20d
      - updated: +5d
      - responded: +2d

  
  ### Issues

  # Open bugs
  bugs:
    name: Open bugs
    type: issue
    resolution: ~ fix that bug ~
    fiters:
      - label: "bug"

  many-reactions:
    name: "many reactions, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">0.75"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  many-commenters:
    name: "many commenters, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - commenters: ">2"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - updated: -7d
      - tag: recv
      - comments-while-closed: ">1"
  
  # Issues needing closure
  issue-stale-needs-info:
    name: "Needs information for over 2 weeks"
    resolution: "Close or remove triage/needs-information label"
    type: issue
    filters:
      - label: triage/needs-information
      - updated: +13d

  issue-stale-support:
    name: "Support request over 30 days old"
    resolution: "Close, or add to triage/long-term-support"
    type: issue
    filters:
      - label: kind/support
      - label: "!long-term-support"
      - updated: +29d

  lifecycle-rotten:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/rotten

  # People with questions
  issue-has-question:
    name: "Overdue answers for a question"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  issue-updated-support:
    name: "Updated support requests"
    resolution: "Move out of support, or add a comment"
    type: issue
    filters:
      - tag: recv
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d