settings:
  name: gosst
  repos:
    - https://github.com/sigstore/cosign
    - https://github.com/sigstore/rekor
    - https://github.com/sigstore/fulcio
    - https://github.com/google/oss-fuzz

collections:
  - id: Pull Requests
    name: Sigstore PRs
    description: >
     Pull requests in need of attention
    rules:
      - prs-cosign
      - prs-fulcio
      - prs-rekor
      - pr-approved-stale
      - pr-unapproved-stale
  - id: PRs - fuzzing
    name: OSS Fuzz PRs
    description: >
      Status of PRs in OSS-Fuzz
    rules:
      - prs-fuzz
      - fuzz-pr-approved-stale
      - fuzz-pr-unapproved-stale
  - id: Fuzzing Issues
    name: Fuzzing Issues
    dedup: true
    description: >
      Status of issues across repos
    rules:
      # People with questions
      - issue-has-question
      - issue-updated-support
      # fuzzing issues
      - fuzz-bugs
      - fuzz-priority
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      - issue-zombies


rules:
  ### Pull requests
  prs-cosign:
    name: "Cosign PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/cosign

  prs-fulcio:
    name: "Fulcio PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/fulcio

  prs-rekor:
    name: "Rekor PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!changes-requested"
    repos:
      - https://github.com/sigstore/rekor

  prs-fuzz:
    name: "OSS Fuzz PRs"
    type: pull_request
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!(changes-requested|draft|approved)"
    repos:
      - https://github.com/google/oss-fuzz

  # PR's needing closure
  fuzz-pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    resolution: "Merge PR"
    type: pull_request
    filters:
      - label: "approved"
      - updated: +2d
      - responded: +1d
    repos:
      - https://github.com/google/oss-fuzz

  fuzz-pr-unapproved-stale:
    name: "Pull Requests: Stale"
    resolution: "Add comment and/or close PR"
    type: pull_request
    filters:
      - created: +3d
      - updated: +2d
      - responded: +1d
      - tag: "!draft"
    repos:
      - https://github.com/google/oss-fuzz

  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    resolution: "Merge PR"
    type: pull_request
    filters:
      - label: "approved"
      - updated: +5d
      - responded: +2d

  pr-unapproved-stale:
    name: "Pull Requests: Stale"
    type: pull_request
    resolution: "Add comment and/or close PR"
    filters:
      - created: +20d
      - updated: +5d
      - responded: +2d

  
  ### Issues

  # Stuff for fuzzing issues
  fuzz-bugs:
    name: "Fuzzing bugs that have not been commented on for 6 months"
    resolution: "comment a status update"
    type: issue
    filters:
      - label: "bug"
      - responded: +180d
      - tag: "!member-last"
    repos:
      - https://github.com/google/oss-fuzz


  fuzz-priority:
    name: "Fuzzing priority issues that have not been commented on for 6 months"
    resolution: "comment a status update"
    type: issue
    filters:
      - label: "priority"
      - responded: +180d
      - tag: "!member-last"
    repos:
      - https://github.com/google/oss-fuzz


  many-reactions:
    name: "many reactions, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">0.75"
      - label: "!priority"

  many-commenters:
    name: "many commenters, low priority"
    resolution: "Upgrade to priority"
    filters:
      - commenters: ">2"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - updated: -7d
      - tag: recv
      - comments-while-closed: ">1"


  # People with questions
  issue-has-question:
    name: "Overdue answers for a question"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv-q
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  issue-updated-support:
    name: "Open support requests"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d
